---
driver:
  name: vagrant

driver_config:
  requre_chef_omnibus: true
  network:
    - ["forwarded_port", {guest: 80, host: 3128}]
    - ["forwarded_port", {guest: 443, host: 3129}]
    - ["private_network", {ip: "172.16.1.3"}]
  synced_folders:
    - [".", "/var/spool/shared-cache"]
  customize:
    memory: 1024
    cpus: 1

provisioner:
  name: chef_zero
  chef_omnibus_url: https://www.chef.io/chef/install.sh

platforms:
  - name: chef/centos-6.5
    driver:
       box: chef/centos-6.5
       box_check_update: 'true'

suites:
  - name: localdev_proxy
    run_list:
      - recipe[default]

